# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_data:
        driver: local

services:
###########################
# Setup the Nginx container
###########################
    nginx:
        image: nginx:latest
        ports:
            - 8080:8888
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html

###########################
# Setup the testing container
###########################
    testing:
        build: ./docker/php/
        volumes_from:
            - php

###########################
# Setup the Database (MySQL) container
###########################
    mysql:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
            
###########################
# Setup the Varnish container
###########################
    varnish:
        build: ./docker/varnish/
        ports:
             - 80:80
        volumes:
            - ./docker/varnish/varnish.vcl:/opt/varnish.vcl
        volumes_from:
            - nginx

